COUNTRIES = ['Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola', 'Antigua and Barbuda', 'Argentina', 'Armenia',
             'Australia', 'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus',
             'Belgium', 'Belize', 'Benin', 'Bhutan', 'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil',
             'Brunei', 'Bulgaria', 'Burkina Faso', 'Burundi', 'Cabo Verde', 'Cambodia', 'Cameroon', 'Canada', 'Chad',
             'Chile', 'China', 'Colombia', 'Comoros', 'Congo', 'Costa Rica', "Cote d'Ivoire", 'Croatia', 'Cuba',
             'Cyprus', 'Czechia', 'Denmark', 'Djibouti', 'Dominica', 'Dominican Republic', 'Ecuador', 'Egypt',
             'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia', 'Eswatini', 'Ethiopia', 'Fiji', 'Finland',
             'France', 'Gabon', 'Gambia', 'Georgia', 'Germany', 'Ghana', 'Greece', 'Grenada', 'Guatemala', 'Guinea',
             'Guinea-Bissau', 'Guyana', 'Haiti', 'Honduras', 'Hungary', 'Iceland', 'India', 'Indonesia', 'Iran',
             'Iraq', 'Ireland', 'Israel', 'Italy', 'Jamaica', 'Japan', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati',
             'Kosovo', 'Kuwait', 'Kyrgyzstan', 'Laos', 'Latvia', 'Lebanon', 'Lesotho', 'Liberia', 'Libya',
             'Liechtenstein', 'Lithuania', 'Luxembourg', 'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali',
             'Malta', 'Marshall Islands', 'Mauritania', 'Mauritius', 'Mexico', 'Micronesia', 'Moldova', 'Monaco',
             'Mongolia', 'Montenegro', 'Morocco', 'Mozambique', 'Myanmar', 'Namibia', 'Nauru', 'Nepal', 'Netherlands',
             'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'North Korea', 'North Macedonia', 'Norway', 'Oman',
             'Pakistan', 'Palau', 'Palestine', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines',
             'Poland', 'Portugal', 'Qatar', 'Romania', 'Russia', 'Rwanda', 'Saint Lucia', 'Samoa', 'San Marino',
             'Saudi Arabia', 'Senegal', 'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore', 'Slovakia', 'Slovenia',
             'Solomon Islands', 'Somalia', 'South Africa', 'South Korea', 'South Sudan', 'Spain', 'Sri Lanka', 'Sudan',
             'Suriname', 'Sweden', 'Switzerland', 'Syria', 'Taiwan', 'Tajikistan', 'Tanzania', 'Thailand',
             'Timor-Leste', 'Togo', 'Tonga', 'Trinidad and Tobago', 'Tunisia', 'Turkey', 'Turkmenistan', 'Tuvalu',
             'Uganda', 'Ukraine', 'UAE', 'UK', 'USA', 'Uruguay', 'Uzbekistan', 'Vanuatu', 'Venezuela', 'Vietnam',
             'Yemen', 'Zambia', 'Zimbabwe']

NAMES = ['Aaron', 'Aaron', 'Abe', 'Abner', 'Abraham', 'Ace', 'Ace', 'Adric', 'Ahmed', 'Aidan', 'Aiden', 'Aiden',
         'Alastair', 'Albion', 'Alden', 'Aldous', 'Alexander', 'Alf', 'Alfonso', 'Alfred', 'Alvin', 'Alvin', 'Amador',
         'Amare', 'Ambrose', 'Ambrose', 'Amir', 'Amos', 'Anders', 'Anderson', 'Andre', 'Andre', 'Andrew', 'Andris',
         'Ang', 'Angus', 'Angus', 'Anthony', 'Antoine', 'Anton', 'Anwyll', 'Aodhán', 'Apollo', 'Aquila', 'Arbor',
         'Archer', 'Ari', 'Arlo', 'Arlo', 'Arlo', 'Armand', 'Armondo', 'Armstrong', 'Armstrong', 'Arnie', 'Arthur',
         'Arturo', 'Arvin', 'Asa', 'Asher', 'Ashton', 'Ashton', 'Aspen', 'Astro', 'Atlas', 'Atticus', 'Atticus',
         'August', 'Austin', 'Avery', 'Avi', 'Avi', 'Axel', 'Axel', 'Axel', 'Bailey', 'Barney', 'Barrett', 'Barrett',
         'Basil', 'Bassel', 'Baxter', 'Beau', 'Beckett', 'Beckett', 'Beckham', 'Bede', 'Benedict', 'Benjamin', 'Benji',
         'Bennett', 'Bennett', 'Benson', 'Bentley', 'Benton', 'Benton', 'Bergen', 'Bernard', 'Bertram', 'Blaine',
         'Blake', 'Booker', 'Booker', 'Bradley', 'Brady', 'Bram', 'Braxton', 'Braxton', 'Brent', 'Bridger', 'Brogan',
         'Brogan', 'Brookes', 'Brooks', 'Bruce', 'Bryant', 'Buck', 'Burke', 'Cadogan', 'Caleb', 'Callum', 'Cam',
         'Camden', 'Campbell', 'Carlton', 'Carney', 'Carter', 'Carver', 'Cary', 'Cash', 'Caspian', 'Caspian', 'Cato',
         'Cavanaugh', 'Cecil', 'Cecil', 'Cedrick', 'Chandler', 'Chester', 'Chidi', 'Christensen', 'Churchill',
         'Claude', 'Clem', 'Clifford', 'Clyde', 'Clyde', 'Cole', 'Collins', 'Colton', 'Colton', 'Cooper', 'Cornelius',
         'Cornelius', 'Cornell', 'Cosmo', 'Cosmo', 'Crew', 'Crosby', 'Cyril', 'Dai', 'Dale', 'Dalton', 'Damian',
         'Damon', 'Damon', 'Darius', 'Darnell', 'Dashiell', 'Dashiell', 'Dashiell', 'Dawson', 'Dax', 'Daylen', 'Dean',
         'Declan', 'Demetrius', 'Dennis', 'Denzel', 'Desmond', 'Dewey', 'Dewey', 'Dexter', 'Dillon', 'Dion', 'Dru',
         'Duke', 'Eagan', 'Eason', 'Ebbe', 'Eben', 'Edgar', 'Edmond', 'Egil', 'Eli', 'Elian', 'Elie', 'Elijah',
         'Elliot', 'Ellis', 'Elon', 'Emerson', 'Emery', 'Ernest', 'Erskine', 'Esau', 'Essam', 'Ethan', 'Eugene',
         'Evans', 'Everest', 'Everet', 'Ezekiel', 'Ezra', 'Ferdi', 'Finn', 'Fitz', 'Fitzgerald', 'Flick', 'Flynn',
         'Flynn', 'Ford', 'Fox', 'Frances', 'Franklin', 'Gabe', 'Gage', 'Galileo', 'Garrison', 'Gillean', 'Grady',
         'Grant', 'Gray', 'Greyson', 'Grover', 'Gus', 'Gus', 'Gustavo', 'Guy', 'Hamilton', 'Hamnet', 'Harlem',
         'Harley', 'Harnan', 'Harold', 'Harvey', 'Hassan', 'Hayden', 'Hendrix', 'Henley', 'Henning', 'Herb', 'Herbert',
         'Homer', 'Howard', 'Howie', 'Hubert', 'Hudson', 'Hudson', 'Hugh', 'Hugo', 'Hugo', 'Husayn', 'Hyacinth',
         'Idris', 'Iggy', 'Ike', 'Ira', 'Irvin', 'Irving', 'Ishmael', 'Ivan', 'Ivo', 'Izaak', 'Jabaar', 'Jace', 'Jack',
         'Jackson', 'Jacques', 'Jaime', 'Jamal', 'Jasper', 'Javier', 'Jax', 'Jay', 'Jayden', 'Jean', 'Jedediah',
         'Jeremiah', 'Jericho', 'Jermaine', 'Jerry', 'Jessie', 'Jett', 'Julius', 'Jupiter', 'Keanu', 'Keith',
         'Kenneth', 'Kent', 'Khalid', 'King', 'Knox', 'Kye', 'Laird', 'Landen', 'Langston', 'Lawrence', 'Lawson',
         'Lee', 'Legend', 'Leighton', 'Leo', 'Leon', 'Leonardo', 'Leonidas', 'Leroy', 'Lester', 'Lex', 'Liam',
         'Linden', 'Logan', 'Lonnie', 'Lowell', 'Luca', 'Luigi', 'Lyle', 'Lynx', 'Maddox', 'Malakai', 'Malcolm',
         'Manuel', 'Marcel', 'Marco', 'Marcus', 'Mario', 'Marion', 'Mars', 'Marv', 'Mason', 'Matteo', 'Matthias',
         'Maurice', 'Maynard', 'McKenzie', 'Memphis', 'Merrick', 'Meyer', 'Micah', 'Micah', 'Mies', 'Miguel', 'Miles',
         'Milo', 'Milo', 'Milton', 'Misha', 'Moses', 'Naeem', 'Napoleon', 'Nate', 'Nelson', 'Nico', 'Noah', 'Nohea',
         'Nolen', 'Norman', 'Oberon', 'Octavio', 'Oliver', 'Ollie', 'Omar', 'Orion', 'Orme', 'Oscar', 'Otis', 'Owen',
         'Parker', 'Peak', 'Penn', 'Perry', 'Peyton', 'Phoenix', 'Pierre', 'Pike', 'Preston', 'Prince', 'Puma',
         'Quaid', 'Quinn', 'Raffiel', 'Raiden', 'Ramone', 'Randall', 'Raphael', 'Ray', 'Reese', 'Reggie', 'Reginald',
         'Remington', 'Reynolds', 'Riaz', 'Robert', 'Rocket', 'Roderick', 'Roman', 'Romare', 'Rome', 'Ronin', 'Ross',
         'Rufus', 'Russell', 'Ryder', 'Ryder', 'Samson', 'Samuel', 'Sawyer', 'Saxon', 'Scout', 'Scout', 'Seamus',
         'Shane', 'Shaw', 'Silas', 'Solar', 'Summit', 'Tancredi', 'Tao', 'Terrell', 'Terrence', 'Thaddeus', 'Theo',
         'Thurman', 'Tracy', 'Trent', 'Tripp', 'Tristan', 'Tupper', 'Ty', 'Tyl', 'Vance', 'Vermont', 'Vin', 'Walker',
         'Ward', 'Warren', 'Washington', 'Waylon', 'Wells', 'Wesley', 'Weston', 'Wilder', 'Wilder', 'Willie',
         'Willson', 'Wing', 'Winslow', 'Wolf', 'Wyatt', 'Xander', 'Zander', 'Zane', 'Zaxton', 'Zayden', 'Zephyr']
